namespace VA.CMS.Infrastructure.ContentTypes;

/// <summary>
/// Generates scaffolded C# content type definition files for the VA CMS.
/// Implements the core logic for `vacms content-type scaffold &lt;Name&gt;` (FR-DEV-06).
///
/// The generated file:
/// - Derives from <c>ContentTypeDefinitionBase</c>
/// - Is placed in the current working directory under
///   <c>ContentTypes/{PascalName}TypeDefinition.cs</c>
/// - Compiles without modification (all required overrides are concrete)
/// </summary>
public static class ScaffoldService
{
    /// <summary>
    /// Scaffolds a content type definition file.
    /// </summary>
    /// <param name="name">
    /// The PascalCase type name supplied by the developer, e.g. "NewsArticle".
    /// Leading/trailing whitespace is trimmed. The snake_case machine name and
    /// display name are derived automatically.
    /// </param>
    /// <param name="outputDir">
    /// Directory in which to create the file. Defaults to the current working directory.
    /// </param>
    /// <returns>The absolute path of the generated file.</returns>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="name"/> is blank or contains characters that are
    /// invalid in a C# identifier.
    /// </exception>
    public static string Scaffold(string name, string? outputDir = null)
    {
        name = (name ?? throw new ArgumentNullException(nameof(name))).Trim();

        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentException("Type name must not be blank.", nameof(name));

        // Validate: must be a valid simple C# identifier (PascalCase, letters+digits only,
        // must start with a letter).
        if (!IsValidIdentifier(name))
            throw new ArgumentException(
                $"'{name}' is not a valid C# identifier. " +
                "Use PascalCase letters and digits only, starting with a letter (e.g. NewsArticle).",
                nameof(name));

        var className     = $"{name}TypeDefinition";
        var snakeName     = ToSnakeCase(name);
        var displayName   = ToDisplayName(name);
        var templateId    = $"{name}Template";
        var fileName      = $"{className}.cs";

        outputDir ??= Directory.GetCurrentDirectory();
        var typeDir = Path.Combine(outputDir, "ContentTypes");
        Directory.CreateDirectory(typeDir);

        var filePath = Path.Combine(typeDir, fileName);

        var content = GenerateSource(className, snakeName, displayName, templateId);
        File.WriteAllText(filePath, content);

        return filePath;
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    public static string GenerateSource(
        string className,
        string snakeName,
        string displayName,
        string templateId)
    {
        return $@"using VA.CMS.Infrastructure.ContentTypes;

namespace VA.CMS.ContentTypes;

/// <summary>
/// Scaffolded content type definition for {displayName}.
/// Generated by `vacms content-type scaffold` — customise fields as needed.
/// </summary>
public sealed class {className} : ContentTypeDefinitionBase
{{
    public override string  Name        => ""{snakeName}"";
    public override string  DisplayName => ""{displayName}"";
    public override string? TemplateId  => ""{templateId}"";
    public override bool    AllowWorkflow => true;

    public override IReadOnlyList<FieldDefinition> Fields =>
    [
        new FieldDefinition(""title"",   FieldType.ShortText, required: true, maxLength: 200),
        new FieldDefinition(""summary"", FieldType.LongText,  required: false, maxLength: 500),
        new FieldDefinition(""body"",    FieldType.RichText,  required: true),
    ];
}}
";
    }

    public static bool IsValidIdentifier(string name)
    {
        if (name.Length == 0) return false;
        if (!char.IsLetter(name[0])) return false;
        foreach (var c in name)
            if (!char.IsLetterOrDigit(c))
                return false;
        return true;
    }

    /// <summary>Converts PascalCase to snake_case.</summary>
    public static string ToSnakeCase(string name)
    {
        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (char.IsUpper(c) && i > 0)
                sb.Append('_');
            sb.Append(char.ToLowerInvariant(c));
        }
        return sb.ToString();
    }

    /// <summary>Converts PascalCase to a space-separated display name.</summary>
    public static string ToDisplayName(string name)
    {
        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (char.IsUpper(c) && i > 0)
                sb.Append(' ');
            sb.Append(c);
        }
        return sb.ToString();
    }
}
