/**
 * Vite plugin (#162): after `vite build`, write dist/web.config for IIS with the
 * SPA fallback rule and the security headers from src/security/csp.ts, then
 * refuse the build if index.html contains an inline <script> (the CSP has no
 * hashes, so an inline script would be blocked in production).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Plugin } from 'vite';
import { ADMIN_SECURITY_HEADERS, buildAdminCsp } from './src/security/csp';

const xml = (s: string): string => s.replace(/&/g, '&amp;').replace(/'/g, '&apos;').replace(/"/g, '&quot;');

export function renderWebConfig(): string {
  const headers: Record<string, string> = {
    'Content-Security-Policy': buildAdminCsp(),
    ...ADMIN_SECURITY_HEADERS,
    // Covers the static assets; the API sets the same header on /api responses.
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  };
  const adds = Object.entries(headers)
    .map(([name, value]) => `        <add name="${name}" value="${xml(value)}" />`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by iis-web-config.plugin.ts during \`vite build\` (#162). Do not edit by hand. -->
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="SPA Fallback" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="index.html" />
        </rule>
      </rules>
    </rewrite>
    <httpProtocol>
      <customHeaders>
        <remove name="X-Powered-By" />
${adds}
      </customHeaders>
    </httpProtocol>
    <staticContent>
      <mimeMap fileExtension=".webmanifest" mimeType="application/manifest+json" />
    </staticContent>
  </system.webServer>
</configuration>
`;
}

export function iisWebConfig(): Plugin {
  let outDir = 'dist';
  return {
    name: 'va-cms-iis-web-config',
    apply: 'build',
    configResolved(config) {
      outDir = config.build.outDir;
    },
    closeBundle() {
      const html = readFileSync(join(outDir, 'index.html'), 'utf8');
      const inline = html.match(/<script(?![^>]*\bsrc=)[^>]*>/g);
      if (inline) {
        throw new Error(`index.html contains ${inline.length} inline <script> tag(s); the CSP (script-src 'self') would block them.`);
      }
      writeFileSync(join(outDir, 'web.config'), renderWebConfig(), 'utf8');
    },
  };
}
